In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
zeolite = "MFI-0"
#df = pd.read_csv("data-full/%s-prod.csv" % zeolite)
#compositions = np.loadtxt("compositions.txt")
df = pd.read_csv("data-binary-ternary/%s/fort12.csv" % zeolite)
print(df.shape)

(16640, 24)

In [20]:
temperatures = [450, 485, 525, 573, 630, 700, 788, 900]

def get_state(df, n_comp=8):
    paths = [x.split('/')[1].split("-") for x in df["Path"].values]
    pid = [int(x[0][1]) for x in paths]
    temperature = [temperatures[int(x[1][1])] for x in paths]
    df = df.drop("Path", axis=1)
    df.insert(0, "Pressure_id", pid)
    df.insert(1, "Temperature", temperature)
    df.insert(2, "cid", [int(x[2][1:]) for x in paths])
    for i in range(n_comp):
        df.insert(i + 2, "Init mol %d" % i, (df[f"Box 0 mol {i}"] + df[f"Box 1 mol {i}"]).astype(int))
    df = df.groupby(["Temperature", "Pressure_id", "cid"]).mean()
    df = df.droplevel("cid")
    return df

In [21]:
df = get_state(df)

In [22]:
df

                         Init mol 0  Init mol 1  Init mol 2  Init mol 3  \
Temperature Pressure_id
450         0                   7.0        11.0        47.0        10.0
            0                   1.0         3.0        48.0        13.0
            0                   3.0        13.0        39.0        15.0
            0                   2.0        20.0        49.0         2.0
            0                   4.0        15.0        44.0         1.0
...                             ...         ...         ...         ...
900         3                  47.0         9.0         2.0        13.0
            3                  53.0         2.0         2.0        15.0
            3                  51.0         1.0        21.0         3.0
            3                  45.0        11.0        14.0         3.0
            3                  48.0         4.0        10.0        10.0

                         Init mol 4  Init mol 5  Init mol 6  Init mol 7  \
Temperature Pressure_id
450         0                   2.0         3.0         0.0         0.0
            0                   8.0         7.0         0.0         0.0
            0                   1.0         9.0         0.0         0.0
            0                   2.0         5.0         0.0         0.0
            0                   6.0        10.0         0.0         0.0
...                             ...         ...         ...         ...
900         3                   1.0         8.0        60.0        10.0
            3                   6.0         2.0        60.0        10.0
            3                   3.0         1.0        60.0        10.0
            3                   1.0         6.0        60.0        10.0
            3                   3.0         5.0        60.0        10.0

                          Cycles  Box 0 volume  ...  Box 1 energy  \
Temperature Pressure_id                         ...
450         0            52076.0           0.0  ...    794.317148
            0            47939.5           0.0  ...   2556.575079
            0            48319.0           0.0  ...   3412.647056
            0            47580.0           0.0  ...   1650.560244
            0            48841.0           0.0  ...   3842.217815
...                          ...           ...  ...           ...
900         3            31098.5           0.0  ... -19349.161383
            3            32235.0           0.0  ... -23096.686370
            3            32924.0           0.0  ... -26049.131521
            3            33220.5           0.0  ... -22457.826409
            3            31649.5           0.0  ... -21953.292897

                         Box 1 pressure  Box 1 mol 0  Box 1 mol 1  \
Temperature Pressure_id
450         0                  2.494220     6.877088    10.994765
            0                  2.501173     0.980313     2.999192
            0                  2.502940     2.946040    12.995507
            0                  2.502477     1.976260    19.992540
            0                  2.505780     3.934331    14.997744
...                                 ...          ...          ...
900         3                802.404264    46.967461     8.999236
            3                801.197323    52.958303     1.999877
            3                800.023622    50.956734     0.999985
            3                804.504009    44.967392    10.999068
            3                797.312933    47.966168     3.999796

                         Box 1 mol 2  Box 1 mol 3  Box 1 mol 4  Box 1 mol 5  \
Temperature Pressure_id
450         0              41.323443     9.110869     1.798706     2.826390
            0              42.154268    11.820979     7.228031     6.597827
            0              34.208165    13.586807     0.901979     8.422453
            0              43.607795     1.816833     1.817273     4.777385
            0              38.604778     0.910020     5.416970     9.445619
...                              ...          ...          ...          ...
900         3               1.992981    12.700881     0.993170     7.978910
            3               1.993022    14.652727     5.957677     1.994725
            3              20.921326     2.933501     2.977835     0.997315
            3              13.950708     2.932444     0.993027     5.983211
            3               9.955288     9.767629     2.976539     4.987145

                         Box 1 mol 6  Box 1 mol 7
Temperature Pressure_id
450         0               0.000000     0.000000
            0               0.000000     0.000000
            0               0.000000     0.000000
            0               0.000000     0.000000
            0               0.000000     0.000000
...                              ...          ...
900         3              57.378362     9.207498
            3              57.356533     9.210413
            3              57.350966     9.217778
            3              57.425403     9.233512
            3              57.402085     9.229411

[27648 rows x 31 columns]

In [23]:
df.to_csv("data-full/%s.csv" % zeolite)
#df.to_csv("data-binary-ternary/%s.csv" % zeolite)